# Generated by Django 6.0.3 on 2026-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("resume_text", models.TextField()),
                ("ats_score", models.FloatField(blank=True, null=True)),
                ("skill_score", models.FloatField(blank=True, null=True)),
                ("experience_score", models.FloatField(blank=True, null=True)),
                ("project_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
