# Generated by Django 5.2.12 on 2026-03-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_ai", "0002_alter_candidate_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="skills",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
