# Generated by Django 5.2.12 on 2026-03-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resume_ai", "0003_candidate_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="embedding",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
